### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by yokirito** [jlucaso1/crunchyroll-quasar#6]
Gostei muito do seu projeto, quando irá dar continuidade?

**Comment by jlucaso1** [comment]
Estou tentando organizar umas funcionalidades para por nele, porém iria ter que refatorar quase todo o código e isso leva um pouco de tempo. Se tiver alguma sugestão ou algo que mudaria pode ficar a vontade.

**Comment by yokirito** [comment]
Era bom por só uma conta premium para todos os usuários, sacas? Você por um acaso teria discord, se sim, poderia mandar aqui?

**Comment by yokirito** [comment]
Eu e um amigo meu temos algumas ideais, se quiser me chama no discord.
Kirito#5305
